### ISSUE TITLE
Linked assemblies should not be copied to output directory

### ISSUE THREAD

**Issue by AArnott** [NuGet/Samples#13]
Using this sample as a template, the package's assembly may still be copied to the app's output directory. This is _not_ desirable and can actually be exactly *not* what you want.

**Comment by karann-msft** [comment]
Which sample specifically are you talking about?

**Comment by AArnott** [comment]
Sorry... I didn't realize there were several in one repo. 

I was referring to this one:
https://github.com/NuGet/Samples/blob/master/NuGet.Samples.Interop/NuGet.Samples.Interop.targets#L13-L15

**Comment by karann-msft** [comment]
@nkolev92 you wanna take this one.
