### ISSUE TITLE
Invalid XML in NativePackage .targets files in ExtensionSDKasNuGetPackage Sample

### ISSUE THREAD

**Issue by TheRusstler** [NuGet/Samples#16]
![xml](https://user-images.githubusercontent.com/8938396/33661716-0d6aeeea-da81-11e7-9f05-e2a85b32607c.png)

- Opening Target tag on line 10 is not closed resulting in invalid XML
- Build fails when importing the NativePackage NuGet package into a new UWP application

**Comment by phraemer** [comment]
The samples really should be working.
Can someone please try them all out?

Thanks!

**Comment by karann-msft** [comment]
@phraemer can you start a PR. We'll take a look.

**Comment by phraemer** [comment]
Hi,

I've fixed the `ExtensionSDKasNuGetPackage` examples in this PR
https://github.com/NuGet/Samples/pull/26

**Comment by phraemer** [comment]
@karann-msft any chance you'll take a look at the PR?

**Comment by phraemer** [comment]
Anyone at all got time to review and merge my PR?
Seems a shame to have broken examples.

**Comment by karann-msft** [comment]
@phraemer thanks for the PR and apologies that it took us this long to get it merged.

**Comment by phraemer** [comment]
No worries @karann-msft ! and thanks for merging
