### ISSUE TITLE
WinRT information: Class not registered

### ISSUE THREAD

**Issue by yunfandev** [NuGet/Samples#19]
Hi ,

I try to build a nuget package with [ExtensionSDKasNuGetPackage](https://github.com/NuGet/Samples/tree/master/ExtensionSDKasNuGetPackage), and install the package in a c++ project. But i got the error:
>  thrown at 0x73E508B2 in BlendNative.exe: Microsoft C++ exception: Platform::ClassNotRegisteredException ^ at memory location 0x0678D02C. HRESULT:0x80040154 Class not registered
WinRT information: Class not registered

I try to reference the c# runtime component directly, it works well.

In addition, i also want to know, if i add reference to Newtonsoft.Json in c# runtime component, how to package the component as a Nuget package.

**Comment by karann-msft** [comment]
Closing as non reproducible. For other queries, please open an issue on the home repo.
