### ISSUE TITLE
ContentFilesExample problems

### ISSUE THREAD

**Issue by conficient** [NuGet/Samples#21]
I am trying to understand the new ContentFiles feature, so I created a test solution with .NET Framework 4.7.1, 4.7.2, .NET Standard 2 and .NET Core 2.0 projects. All are set up to use `PackageReference` rather than `packages.config`. https://github.com/conficient/ContentFileTest 

I added the ContentFilesSample Nuget package to all four projects in the solution. 

This appeared to work in the .NET Standard and Core projects: the `data.txt`, `ExampleInternals.cs` files and the `tools` folders were created. However the `images` folder was not.

The Framework projects were unchanged, and had nothing added.  I upgraded the net471/net472 projects to use the new format, and tried again.

This time I got errors: 
```
CSC : error CS2001: Source file 'C:\Users\Howard\.nuget\packages\contentfilesexample\1.0.2\contentFiles\cs\portable-net45+wpa81+wp8+win8\ExampleInternals.cs' could not be found.
```
I checked this folder and found this:
![image](https://user-images.githubusercontent.com/454494/39753458-c28a6c9e-52b6-11e8-99a8-32a65922ace4.png)

Bugs:
- [ ] The `images` folder/files were not created in either NETStandard/Core projects
- [ ] Package content not working with .NET Framework apps
- [ ] package folder encoding not working?

**Comment by karann-msft** [comment]
Please create issues on our Home repo.
