### ISSUE TITLE
Querying most downloaded packages from nuget.org

### ISSUE THREAD

**Issue by mixandmatch025** [NuGet/Samples#24]
Hi, I'm trying to modify the Nuget.Protocol.Catalog.Sample to download all nugets in nuget.org that have more than a configurable amount of downloads with their dependencies.
I'm a bit confused of how best to approach this. Should I get the number of downloads from the PackageDetailsCatalogLeaf?  If so - how?
Is there a better way to query the API for a list of the most downloaded nugets?

**Comment by loic-sharma** [comment]
There's an undocumented API (meaning that we may change/break this API at any time) that contains the download count of all packages: https://nugetprod0.blob.core.windows.net/ng-search-data/downloads.v1.json

Our search service uses this API to rank search results. See this code: https://github.com/NuGet/NuGet.Services.Metadata/blob/master/src/NuGet.Indexing/Downloads.cs

Let me know if you have any questions.
