### ISSUE TITLE
Sample depends on wrong version of https://www.nuget.org/packages/ClassLibrary/1.0.0/

### ISSUE THREAD

**Issue by OzBob** [NuGet/Samples#7]
https://github.com/NuGet/Samples/blob/master/Satellite-Packages/ConsoleApp/ConsoleApp.csproj#L13
shows a dependency on a nuget package that was built without 'Strings' or referencing net40. (see https://github.com/NuGet/Samples/blob/master/Satellite-Packages/ConsoleApp/ConsoleApp.csproj#L13
only targets netFramework 4.0 client profile.)

https://www.nuget.org/packages/ClassLibrary/1.0.0/ is built with and only has reference to net45 assemblies.

Only @karann-msft can upload a new version of ClassLibrary to nuget!

A pull request that has documentation for referencing a local 'nuget' repository, and references net45- can be created if you wish...

**Comment by karann-msft** [comment]
@OzBob yes please. A PR would be much appreciated. Thanks :-)

**Comment by karann-msft** [comment]
Closing as stale.
