### ISSUE TITLE
Is this only for UWP?  What about WPF or Xamarin Forms?

### ISSUE THREAD

**Issue by kdawg1406** [NuGet/Samples#8]
Is this only for UWP?  What about WPF or Xamarin Forms?

Best, 

Karl

**Comment by karann-msft** [comment]
This samples repo is not targeted at any specific platform. We add samples as and when we see the need to demonstrate new concepts. Like we did with [creating UWP controls and shipping them as a nuget package](https://docs.microsoft.com/en-us/nuget/guides/create-uwp-controls). 

We also invite the community to contribute.

Thanks.
Karan
